language: php

php:
    - 5.6

env:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=latest WP_MULTISITE=1
    - WP_VERSION=4.4.1 WP_MULTISITE=0
    - WP_VERSION=4.4.1 WP_MULTISITE=1
    - WP_VERSION=4.3.3 WP_MULTISITE=0
    - WP_VERSION=4.3.3 WP_MULTISITE=1
    - WP_VERSION=4.2.2 WP_MULTISITE=0
    - WP_VERSION=4.2.2 WP_MULTISITE=1

before_script:
    - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION 

script: phpunit